from . import hr_applicant
from . import hr_candidate
from . import hr_candidate_course
from . import hr_candidate_experience
from . import hr_candidate_language
from . import hr_candidate_school
from . import hr_course
from . import hr_company
from . import hr_institution
from . import hr_job_position
from . import hr_language
from . import hr_skill
from . import hr_study_area
from . import res_country
from . import res_company
from . import res_company_hr_job
from . import res_company_hr_employee
from . import res_company_hr_department
from . import res_company_hr_applicant
from . import res_company_hr_job_contract_type
from . import mail_activity
